### ISSUE TITLE
OmniMIDI crashing application when noteoff delay and override length of notes is enabled.

### ISSUE THREAD

**Issue by cedar515** [KaleidonKep99/Keppy-s-MIDI-Driver#212]
**Problem**
OmniMIDI crashes apps using it when I try to use the synthesizer with **Override length of note events** or **Add delay to note off events** enabled.

**Steps to reproduce**
1. Play a simple midi with the noteoff delays on for about 8 seconds
4. Application crashes (sometimes still running in the background)

**Expected behavior**
No problems with noteoff delays when synthesizer is being used by synthesia or piano from above.

**Screenshots/Videos**
https://user-images.githubusercontent.com/85410306/134231894-bd68fceb-18da-43bc-89f9-11efe11c3876.mp4

**Environment**
 - Operating system: Windows 10 Pro (64-bit)
 - CPU: AMD Athlon II x2 245 (2.9GHz)
 - RAM: 8 GB (Limit of my motherboard)
 - MIDI application: Synthesia 9.0.2495, Piano From Above 1.1.0
 - Version of the driver: 14.6.9

**Additional context**
I think it happens to me only because I'm on old hardware, glad to be lucky I'm not alone if someone also faced this issue.

**Comment by KaleidonKep99** [comment]
Fixed in 14.6.10.

**Comment by cedar515** [comment]
> Fixed in 14.6.10.

Thank you for the fix. But I don't really mean to complicate my issues though, because I have one more issue 😖 (issue existed even before this issue was opened) If its okay to create another issue about it soon or by the next passing calendar days.

**Comment by KaleidonKep99** [comment]
Don't worry, just create another issue about it
