### ISSUE TITLE
BM patch makes pfa silent

### ISSUE THREAD

**Issue by Endermaster3690** [KaleidonKep99/Keppy-s-MIDI-Driver#213]
**Problem**
If I apply the patch at the top when I do the windows multimedia wrapper thing, it makes piano from above silent!

**Steps to reproduce**
Look at Problem

**Expected behavior**
It's gonna make it not make any sound.

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Environment**
 - Operating system: win10
 - CPU: idk
 - RAM: 16gb installed
 - MIDI application: pfa latest version
 - Version of the driver: idk

**Additional context**
if the CPU is my core, then I have an Intel Inside core i3.

**Comment by KaleidonKep99** [comment]
Not enough info, sorry.

**Comment by Endermaster3690** [comment]
![asasdasd](https://user-images.githubusercontent.com/80355301/134582737-f2054d50-41d9-4e74-930f-69f899385f48.png)
![bloxy glitch](https://user-images.githubusercontent.com/80355301/134582758-869e95fc-4b74-4a67-9927-e7f3cb7d8299.png)
![earth's frozen fear for the future](https://user-images.githubusercontent.com/80355301/134582967-fff2fcb0-5fc3-4bc3-b64c-618e9c14ab72.png)

This causes MIDIs to be silent in PFA.

**Comment by KaleidonKep99** [comment]
I also need:
1. The specific version of Windows you're on
2. The specific version of OmniMIDI you're on

**Comment by Endermaster3690** [comment]
> 2. The specific version of OmniMIDI you're on <<<<<<<<<<

how do i see

**Comment by Endermaster3690** [comment]
wait im on 14.6.9 of omnimidi, also here's my pc info
![asasdasd](https://user-images.githubusercontent.com/80355301/134589229-3fede6b0-0f7c-4db4-a900-89835e958426.png)

**Comment by Endermaster3690** [comment]
also i am not using a soundfont

**Comment by Endermaster3690** [comment]
i got a soundfont and the bug's fixed. i dont need any more help

**Comment by KaleidonKep99** [comment]
Okay?...
