### ISSUE TITLE
support sfark files

### ISSUE THREAD

**Issue by Endermaster3690** [KaleidonKep99/Keppy-s-MIDI-Driver#214]
**Is your feature request related to a problem? Please describe.**
i wanna be able to use arachno soundfont. if im correct sf2 only supports 1 instrunent. but its not available in sfz and omni wont show me sfark so uhh

**Describe the solution you'd like**
i wanna use sfark for soundfonts

**Describe alternatives you've considered**
arachnosoft to have an sfz download or something

**Additional context**
no

**Comment by KaleidonKep99** [comment]
SFZ is what only supports one instrument!
SF2 supports multiple instruments and will work fine.

**Comment by Endermaster3690** [comment]
oh i got it backwards. apparently i didnt get arachno i got this weird steinway grand piano for some reason.
