### ISSUE TITLE
Omnimidi no sound

### ISSUE THREAD

**Issue by n0b0py** [KaleidonKep99/Keppy-s-MIDI-Driver#215]
**Problem**
When I try to use omnimidi in pfa the sound never works, even if I add a sound font. I tried reinstalling pfa and omnimidi, but it never worked

**Steps to reproduce**
1. Open pfa
2. Select omnimidi in sound tab
3. Play a midi

**Expected behavior**
To get sound when i select omnimidi.

**Environment**
 - Operating system: Windows 10
 - CPU: i7-6700T (2.80 GHZ)
 - RAM: 7.9 GB
 - MIDI application: Piano from above (Version 1.1.0)
 - Version of the driver: 13.8.2.0

**Comment by Endermaster3690** [comment]
i add the windows multimedia wrapper i think. maybe that'll work.

**Comment by KaleidonKep99** [comment]
Please update your driver first.

**Comment by n0b0py** [comment]
I forgot to check the sound font, but when I check it it gives me an error.
![im good, LEAVE ME ALOVE](https://user-images.githubusercontent.com/92056558/137382660-ad7cde84-2b48-4fdb-b2e7-35cb09212fa5.png)

**Comment by Endermaster3690** [comment]
> Please update your driver first.

**Comment by n0b0py** [comment]
idk how to update it

**Comment by Endermaster3690** [comment]
ok, idk how to help u then.

**Comment by n0b0py** [comment]
WAIT I FIXED IT! I just was not on the right audio output

**Comment by KaleidonKep99** [comment]
Nice.
