### ISSUE TITLE
New versions not seen by OmniMIDI

### ISSUE THREAD

**Issue by Creatinator512** [KaleidonKep99/Keppy-s-MIDI-Driver#217]
**Problem**
The system that detects updates in OM seems to not be finding any new versions.

**Steps to reproduce**
1.) Downgrade to a lower version of OM. (Versions 14.6.0 to 14.6.10 have this bug, but it may go farther back than I've looked.)
2.) Check for any new updates in the program. (Refreshing the latest version finder or selecting "Check for updates" from the toolbar or changelog are the options I have tried.)

**Expected behavior**
A new version should be found.

**Screenshots/Videos**
![om_updaterNotWorking](https://user-images.githubusercontent.com/78432612/144523359-ea96deb2-6dc5-4724-a87a-fc660c240cec.png)

**Environment**
 - Operating system: Windows 10 Pro, Version 21H1
 - CPU: Intel(R) Pentium(R) CPU G850 @ 2.90GHz (2 CPUs), ~2.9GHz
 - RAM: 4 GB
 - Version of the driver: 14.6.10

**Additional context**
I'm sure it isn't my internet connection, as it worked fine when connecting to the GitHub website, however I don't know what rate limiting is and how to fix it.

**Comment by KaleidonKep99** [comment]
Seems like the API broke, I can't really do much about it since it's all code written by GitHub.
I'll fix it in the latest release, but everyone will be forced to upgrade on their own.

**Comment by KaleidonKep99** [comment]
Fixed in version .12.
Yeah, the API has been changed, which broke older releases of Octokit (The extension I use to check for updates through the configurator).

**Comment by Creatinator512** [comment]
Okay. Thank you for fixing it. I also want to thank you for all the time and hard work you've put into OmniMIDI to fix any bugs and improve. This is truly a great MIDI Output driver and it would not be where it is today without your commitment!

**Comment by KaleidonKep99** [comment]
That's something really nice to hear, especially when you're lacking the motivation to work on your own projects...
Thank you a lot for your kind words! I hope Shakra won't disappoint anyone.
