### ISSUE TITLE
When opening anything with midi there's an "error" with the app.

### ISSUE THREAD

**Issue by n0b0py** [KaleidonKep99/Keppy-s-MIDI-Driver#219]
I was normally opening a midi app when the app gave me a error non-stop until I close it, if I try to close the error the error just reopens.

I don't know how to fix this nor do I know what it means, before this only happened when the computer went to sleep, and I was perfectly fine with that, it also did not freeze my whole browser if I went on a midi app for the browser, but now it does.

I did not change any settings with it, it just started happening randomly.

Environment:
OS: Windows 10 Pro
Memory: 7.9 GB
SSD: 106 Billion bytes or 99.4 GB
SSD Free Space (as of 12/28/2021): > 2.5 GB
CPU: Intel Core i7-6700T (Cores 4) (Logical processors 8)
MIDI App: Every MIDI App

Steps to reproduce:
I don't know, it just started happening randomly.

Video:
(video too big to put in: 41.3 mb, i'll put 2 screenshots instead, once the limit is bigger i'll put it in, sorry if there's only one screenshot i'll put the next one in after because it crashes google.)

![error](https://user-images.githubusercontent.com/92056558/147587007-f4390f40-8612-4bd8-82d6-25a11b1f2ee0.png)
![error2](https://user-images.githubusercontent.com/92056558/147587490-9e831ca9-60d0-45de-a31e-6747fdd5dcdd.png)

**Comment by KaleidonKep99** [comment]
As the error says, the selected output device isn’t available anymore.
You can choose a different audio device from the output settings in the configurator. (Next to the audio engine selection box)

**Comment by n0b0py** [comment]
Can you show me where it is?

**Comment by KaleidonKep99** [comment]
> Can you show me where it is?

![image](https://user-images.githubusercontent.com/11065274/147729237-454ced46-9f41-40e9-8c7d-8efd99c20b44.png)

**Comment by n0b0py** [comment]
It was the Windows sound input, for some reason it just breaks randomly and it stops MIDI from happening and I have to do this troubleshooting thing to get it working again.
