### ISSUE TITLE
OmniMIDI crashes programs for no reason

### ISSUE THREAD

**Issue by LexonBlackzz** [KaleidonKep99/Keppy-s-MIDI-Driver#223]
2 days ago PFA crashed because of an unknown reason, caused by OmniMIDI (or MMdevAPI.dll)
FL Studio 20.7.2 also crashed, caused by OmniMIDI (or MMDevAPI.dll)
Kiva ALSO crashed, caused by OmniMIDI (or MMDevAPI.dll), Guru meditation
I am using version 14.6.13
Here are the crash event logs:
Kiva: 
![image](https://user-images.githubusercontent.com/98592761/152943905-9dbae589-1b96-4d85-bbb4-3df181178ad4.png)

FL Studio:
![image](https://user-images.githubusercontent.com/98592761/152944000-0207db27-d66d-4335-8f57-5d0938e46e69.png)

PFA:
![image](https://user-images.githubusercontent.com/98592761/152944064-b42d11b5-ce63-4628-bdbd-2b8f6d4da434.png)

Crashes also happened by OmniMIDI in older versions too. Please fix OmniMIDI like it was before because this is too frequent,

**Comment by KaleidonKep99** [comment]
I can't do anything unless you enable the debug log in the configurator.

Please enable it by checking this option in the configurator:
![image](https://user-images.githubusercontent.com/11065274/153702671-7c33b893-74ec-4eda-9780-f99f70327c75.png)

Then send me the latest log, which you can find by clicking "Debug logs folder" next to the option you enabled earlier.

**Comment by KaleidonKep99** [comment]
Closed for missing information.
