### ISSUE TITLE
Is hide using in fixed

### ISSUE THREAD

**Issue by OldJERN8322** [KaleidonKep99/Keppy-s-MIDI-Driver#224]
**Problem**

**Steps to reproduce**
Idk in this open i nithing.

**Expected behavior**

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Environment**
 - Operating system: Windows 10 (version 20H2)
 - CPU: Intal(R) N4000 @ 1.10GHz
 - RAM: 4Gb (using in 3,8Gb)
 - MIDI application: Other (Version N/A)
 - Version of the driver: 4.4.1.4

**Additional context**
Please help in added fixed this hide :(

https://user-images.githubusercontent.com/99561059/153727812-b3e59227-3af7-454d-9e77-f8b98a062e95.mp4

And this

![Bug 1](https://user-images.githubusercontent.com/99561059/153728465-6ff48e8b-aee9-4725-ae57-266b6f674484.png)

**Comment by KaleidonKep99** [comment]
Sorry, I don't support Keppy's Synthesizer.
Update to the latest version of OmniMIDI (after uninstalling Keppy's Synthesizer), then try again.

**Comment by OldJERN8322** [comment]
ok but this in not laggy on OmniMIDI in version 13.8.6.0
