### ISSUE TITLE
When I updated, midi apps don't seem to work anymore.

### ISSUE THREAD

**Issue by n0b0py** [KaleidonKep99/Keppy-s-MIDI-Driver#225]
**Problem**
Midi apps refuse to open with a error message saying "Failed to initialize KDMAPI! Press OK to quit.", I don't know what this means, it worked perfectly before a updated to the latest version, I saved my data and did everything it told me to do. Is it just me or are other people having this problem? And I also selected the stable update.

**Steps to reproduce**
1. Update OmniMIDI
2. See error (I don't know if it happens to everyone, like I said)

**Expected behavior**
To have extra features when I update to mess around with.

**Screenshots/Videos**
![nooo](https://user-images.githubusercontent.com/92056558/158026839-fd715892-dd96-46f0-8027-f3b52603c90f.JPG)

**Environment**
 - Operating system: Windows 10 Pro
 - CPU: i7-6700 4 cores, 8 logical processors, 2.80 GHz
 - RAM: 8GB
 - MIDI application: PFA, PFA VISKHANG, Zenith (Version ???)
 - Version of the driver: 14.6.13

**Additional context**
May be disk space, I rarely have even 1 GB of disk space!

**Comment by KaleidonKep99** [comment]
Those errors mean that you're using an outdated version of WinMMWRP.

Reapplying the wrapper to the apps will fix the issue.

**Comment by n0b0py** [comment]
Oh thanks, I did not know I had to repatch.
