### ISSUE TITLE
Request to add gain/volume past 100% or control on soundfont settings

### ISSUE THREAD

**Issue by RotKingJoey** [KaleidonKep99/Keppy-s-MIDI-Driver#227]
**Is your feature request related to a problem? Please describe.**
When utilizing soundfonts with lower volume than is average, such as the Rolland SC-55 based one found here, (https://github.com/trevor0402/SC55Soundfont) it is nearly impossible to mix standard music sources and midi playback (such as when utilizing GZDoom, which can sometimes go back and forth between the two).

**Describe the solution you'd like**
I believe it would be useful to offer the ability to do either of these two things:
1. A check mark/switch that allows you to increase the volume control within the application's settings past the default 100% (up to 1000% would likely resolve most soundfonts that experience this issue)
2. Offer the ability to change an individual soundfont's volume level and by extension past 100% like above up to 1000% within a right-click menu or bank/preset values. This would be even more ideal as you'd be able to tune to match the volume levels with other loaded soundfonts that don't require this consideration.

**Describe alternatives you've considered**
While VirtualMidiSynth offers the ability to configure this within the soundfont properties, this is less than ideal for a few reasons. Firstly the volume limit caps at 500%, which can surprisingly be a bit low depending on the source. Additionally, due to the way that VirtualMidiSynth runs the virtual midi device in it's own separate process, it can complicate volume mixing in Windows and be finicky with capture software.
For these reasons, I overall believe that OmniMIDI is the better choice of the two for my needs, I just believe it would be more ideal if it offered the ability to control it's output volume further. Thank you for reading my request.

**Comment by KaleidonKep99** [comment]
Hi.

OmniMIDI already allows you to increase the output volume above 100%, you can access that by right-clicking the volume knob!
![image](https://user-images.githubusercontent.com/11065274/162701521-2754cef4-ea8c-41a5-b854-41615dee1ea9.png)

It is currently capped at 500%, but I can increase the cap to 1000% in the next update.

**Comment by RotKingJoey** [comment]
Doh, thanks for pointing this out. Noted, and appreciate the cap increase!
