### ISSUE TITLE
EventsProcesser crashes Zenith

### ISSUE THREAD

**Issue by LexonBlackzz** [KaleidonKep99/Keppy-s-MIDI-Driver#228]
**Problem**
EventsProcesser makes an unrecoverable crash on Zenith

**Steps to reproduce**
1. Play any MIDI in Zenith
2. Play preview for around 15 seconds, then close the preview

**Expected behavior**
The program shouldn't crash while closing the preview window.

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/98592761/162616486-2e8d0622-3ac5-437e-8522-b5a2d37d4f14.png)

**Environment**
 - Operating system: Windows 11 Education
 - CPU: AMD Ryzen 5 4500U 
 - RAM: 8 GB 
 - MIDI application: Zenith 2.1.5
 - Version of the driver: 14.6.12 and newer

**Comment by KaleidonKep99** [comment]
I'll look into it.

**Comment by KaleidonKep99** [comment]
Seems to be fixed as of 14.6.13.127.
