### ISSUE TITLE
Middle-clicking while the context menu is open prompts an unhandled exception

### ISSUE THREAD

**Issue by B00ie23** [KaleidonKep99/Keppy-s-MIDI-Driver#230]
**Problem**
This was encountered by accident, when right-clicking to open the context menu, simply middle-clicking while the menu is open brings up an unhandled exception.

**Steps to reproduce**
1. On the configurator, right click any Soundfont to open the context menu.
2. When the context menu is open, do a middle click.
3. The unhandled exception message should appear.

**Expected behavior**
To be honest, I have no idea what the intended behavior is supposed to be.
My guess is that middle-clicking isn't supposed to do anything, see additional context on the bottom.

**Screenshots/Videos**

https://user-images.githubusercontent.com/45867359/163036222-4305e9ca-a4c4-4842-b202-230324e16ea3.mp4

**Environment**
 - Operating system: Windows 11 Home (x64)
 - CPU: AMD Ryzen 5 3600
 - RAM: 16 GB
 - MIDI application: None
 - Version of the driver: 14.6.13 (PR81)

**Additional context**
This does not appear to affect the configurator or OmniMIDI as a whole in any way as it seems to behave like nothing happened when you press continue.

**Comment by KaleidonKep99** [comment]
I'll fix that asap!

**Comment by KaleidonKep99** [comment]
Will be fixed in latest release.

**Comment by KaleidonKep99** [comment]
Fixed in 14.6.14.
