### ISSUE TITLE
[Critical] OmniMIDI is unable to reserve any of the nine x86 or x64 MIDI ports for it's drivers

### ISSUE THREAD

**Issue by B00ie23** [KaleidonKep99/Keppy-s-MIDI-Driver#233]
I'm going to get straight to the point just to post this issue ASAP.
A critical issue is occuring on my end (if not affecting all PR users) after updating to PR97. As stated from the title, OmniMIDI is unable to reserve a port for it's drivers.
The troubleshooter tries to help OmniMIDI reserve a port, but it misses. Running the configurator with elevation does not help.
This issue is exclusive to PR97, earlier versions do not run into this issue.

I lost my GIF attachment somehow, but I will provide one if required.

**Environment**
 - Operating system: Windows 11 Home
 - CPU: AMD Ryzen 5 3600
 - RAM: 16 GB
 - MIDI application: None
 - Version of the driver: 14.6.13 (PR97)

**Comment by B00ie23** [comment]
[This issue](https://github.com/KeppySoftware/OmniMIDI/issues/226#issue-1181984032) may be relevant, but unlike that case, I do not get the "No ports are available" error.

**Comment by KaleidonKep99** [comment]
Yeah, I introduced this bug by accident, together with a bug that causes the wrapper installer to silently fail with no error message.
It will be fixed in the next PR!

**Comment by spritefalcon** [comment]
Can confirm this is a critical bug, was having this issue with the latest update

**Comment by B00ie23** [comment]
PR127 has fixed this issue- at least for me as far as I'm aware. _Thank you Kep!_
Anyone is free to re-open this if it is still occurring for them.
