### ISSUE TITLE
Audacity is compromised by KDMAPI Installation / (Failed to Initialize KDMAPI)

### ISSUE THREAD

**Issue by TheShakant** [KaleidonKep99/Keppy-s-MIDI-Driver#234]
**Problem**
A few days ago i had after a crash the Problem that my Audacity doesnt work anymore with the "Open file with" option.
it just crashes with the "KDMAPI Failed to Initialize KDMAPI! Press OK to Quit" and then Crashes the APP entirely error.
i can still start Audacity however with NO Problems if i start it manually. 

Deinstalling Omnimidi / Reinstall, Reboot, doesnt work. 
Same with Audacity.
Blacklisting, wont work. 

After deinstalling Omnimidi it just says "OpenlibraryW cannot be used, please make sure you are using Omnimidi etc."
Fun fact : I deactivated Midi in Audacity, Doesnt work. KDMAPI still hooks, which is unpleasantly annoying to me.

How to Deinstall / Fix KDMAPI ??

**Steps to reproduce**
1. Get Omnimidi , have Audacity Installed. Use Omnimidi while provoke a Crash on the Audiolevel. 
2. Open File With Audacity 
3. See Error

**Expected behavior**
That Audacity should work as intended, KDMAPI should probably ignore

**Screenshots/Videos**
Doesnt know how to add here yet, sorry.

**Environment**
 - MIDI application: Audacity (Version 3.1.3)

OmniMIDI version 14.6.13.0
========= Debug information =========
Driver version: 14.6.13.0
Current MIDI app: None (N/A)
Active voices: 0
RH/WH position: 0/0 (0)
Rendering time: 0,0%
Unavailable Audio latency:
App's working set size: No usage
App's handles count: 0 handles
KDMAPI status: Unavailable

======== System  information ========
Driver version: 14.6.13.0
Operating system: Windows 10 Pro (10.0.19043.1706, AMD64)
CPU: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (AMD64 architecture)
CPU info: GenuineIntel, 4 cores, 4 threads, 3,50GHz (3501MHz)
GPU: NVIDIA GeForce GTX 1060 3GB
GPU chip: NVIDIA GeForce GTX 1060 3GB
GPU info: 3072MB VRAM, driver version 27.21.14.6674
Total memory: 16326MB (17.120.075.776 bytes)
Available memory: 11935MB (73,1%, 12.515.516.416 bytes)

**Additional context**
Whitelisting should be an Option too. :)

**Comment by KaleidonKep99** [comment]
Audacity does not require the Windows Multimedia Wrapper to work.

Please run the configurator as an administrator, and uninstall it by following these screenshots:
![image](https://user-images.githubusercontent.com/11065274/168828261-8c5b15b7-c18a-4dcf-ba80-805c246fd64f.png)
![image](https://user-images.githubusercontent.com/11065274/168828302-ff4b07e7-7ec5-4ae7-9206-b0d802fd1d04.png)
![image](https://user-images.githubusercontent.com/11065274/168828383-9136c666-1d09-4914-98fa-487b7fe48e6b.png)
![image](https://user-images.githubusercontent.com/11065274/168828479-89633acf-905f-4c46-b18f-a02285f4fc59.png)

> **Additional context** Whitelisting should be an Option too. :)

Adding a whitelist system won't make a difference, if the user installs the Windows Multimedia Wrapper to applications that don't really make use of it. The wrapper loads OmniMIDI when its library gets loaded by the program, and if it fails to hook to it, it will crash.

**Comment by TheShakant** [comment]
Audacity wasnt even patched, and i did follow your guide. 
No change at all still : 

KDMAPI ERROR
Failed to initialize KDMAPI!
Press OK To Quit. 

After that, another crash comes up which is audacity couldnt be executed properly. 
Audacity starting normal if i start it normal. 

But if i click an MP3 or FLAC or file and open it via context menu : Open With => Audacity 
then KDMAPI Error will occur all the time. Like it auto-hooks. 

How can i fix this ?

**Comment by KaleidonKep99** [comment]
Again, if it's complaining about not being able to load KDMAPI, it means that it has been somehow patched.
Check in the program's directory if there's a file called **winmm.dll**, and delete it manually.

**Comment by TheShakant** [comment]
Nope, there is no Winmm.dll in the Audacity folder. 
but why does KDMAPI try to hook with it via open files dialogue , but not without it, that question is still unanswered. 

Audacity had a Portmidi file, which is part of the program.
Is it maybe because Audacity has MME Mode integrated ? Otherwise im pretty clueless.

**Comment by KaleidonKep99** [comment]
Again, KDMAPI is not natively supported in Audacity, and if the wrapper is not installed alongside it, then there's no way for the program to make use of the API.

I don't know what's causing this behavior, but I can definitely say that if winmm.dll is missing from the directory, then there's something wrong in your Windows install.

You could try and check through Process Hacker if there's an extra winmm.dll being loaded by Audacity, honestly I have no idea.
![image](https://user-images.githubusercontent.com/11065274/169404333-c2440e65-eeed-4e33-87b8-1f4ac0828a47.png)

**Comment by TheShakant** [comment]
I had 2 Audactiy installations.
And one of them got an extra Winmm.dll which is really weird, it was from 2020, i dont remember for what i got it, or even why i had it in the folder of Audacity.
deleted it and it ran just fine. Windows picked different audacity installations (i guess?) because one version was Portable only. so, Error happened on the Windows side. 

after deleting (isolating) it it runs just fine.
Thanks for your patience, help and time, i really appreciate it 👍  

Nice work :)

**Comment by KaleidonKep99** [comment]
I guess you patched it someday and then forgot to unpatch it!
I'm glad that you managed to fix it.

Closed!
