### ISSUE TITLE
No driver in Windows server 2012

### ISSUE THREAD

**Issue by Zel9278** [KaleidonKep99/Keppy-s-MIDI-Driver#236]
**Problem**
After installing OmniMIDI on Windows server 2012, it crashes when installing MIDI drivers.

**Steps to reproduce**
1. Install Omnimidi installer from latest release page
2. Run installer
3. Follow the steps to proceed with the installation.
4. See error (midi driver installation)

**Expected behavior**
Driver must be well installed.

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/530902417395548175/993467694680637460/Desktop_2022.07.04_-_19.45.15.01.mp4

**Environment**
 - Operating system: Windows Server 2012 R2 (6.3 Build 9000)
 - CPU: Intel Xeon E3-1220 v3
 - RAM: 16GB
 - MIDI application: not
 - Version of the driver: 14.6.13

**Additional context**
not

**Comment by KaleidonKep99** [comment]
I forgot to post an answer here, but I'm actively working on fixing the bug.

**Comment by KaleidonKep99** [comment]
It's been a while, but it should work now.
