### ISSUE TITLE
LSB banks are not loaded properly

### ISSUE THREAD

**Issue by hakerg** [KaleidonKep99/Keppy-s-MIDI-Driver#240]
Property "sf.desblsb" is not recognized properly by the driver—it's recognized as "sf.desb". It can be fixed by replacing
`TempLine.find(L"sf.desb") == 0`
wth
`TempLine.find(L"sf.desb ") == 0`
in `SoundFontLoader.h` in OmniMIDI solution.

**Comment by KaleidonKep99** [comment]
Will fix, thank you!
