### ISSUE TITLE
Removing soundfonts

### ISSUE THREAD

**Issue by hakerg** [KaleidonKep99/Keppy-s-MIDI-Driver#243]
Please add a possibility to remove single soundfonts - currently you have to clear the whole list and add every soundfont again or edit the .sf file
![image](https://user-images.githubusercontent.com/30211038/190897610-911aa809-04d9-4219-8011-296369308167.png)

**Comment by kiptunor** [comment]
This is not gonna happen ever bc that feature already exists lmfao

To Remove 1 Single soundfont click the minus button on the right top side.
![190897610-911aa809-04d9-4219-8011-296369308167](https://github.com/KeppySoftware/OmniMIDI/assets/92180085/c5c4a081-5dfb-4e8f-9f2b-6ff8793cbef8)
