### ISSUE TITLE
Some MIDI apps are not working at all

### ISSUE THREAD

**Issue by kiptunor** [KaleidonKep99/Keppy-s-MIDI-Driver#245]
**Problem**
The apps that are not working at all with this version of OmniMidi are: 
PFA Viz DX12 build (is not opening at all and no error is shown)
MMvis (this error is shown after loading midis: "Error: Can't prepare Longhdr (errno 11) Long messages will not be available")
(All of these midi players are not showing up any errors after loading midis)
extrasmol 
mmmmidi_mem_d (1) (same as extrasmol)
mmmmidi_mem_d 
mmmmidi_mem_d_ns
mmmmidi_mem_d_ns_-_Copy
mmmmidi_qpcmemd
mmvisd

**Specs**
 - Operating system: Windows 10 Pro, version: 21H2
 - CPU: Intel Core i3 12100
 - RAM: 16gb DDR4 at 3200 MHz
 - MIDI application: PFA Viz XD12, MMVis (idk the exact version number for both but they're latest versions)
 - Version of the driver: 14.614

**Comment by KaleidonKep99** [comment]
Please enable the debug log in OmniMIDI, and post it here.
You can find the logs in `%userprofile%\OmniMIDI\debug`.

**Comment by kiptunor** [comment]
> Please enable the debug log in OmniMIDI, and post it here. You can find the logs in `%userprofile%\OmniMIDI\debug`.

I tried that but I couldn't find any log files for the apps I specified but I tested that with stock PFA and I found that log file.
