### ISSUE TITLE
Omnimidi automatically closes my midi player

### ISSUE THREAD

**Issue by ElwerKarlsson** [KaleidonKep99/Keppy-s-MIDI-Driver#247]
**Problem**
Midi player automatically closes

**Steps to reproduce**
1. Open Kiva
2. switch to Microsoft Tablewave soundfont while having OmniMidi installed
3. Kiva automatically closes

**Expected behavior**
I didn't expect the app to crash my midi player, midi editor. I expected the app to just work like a normal software adding the feature to output midi to soundfonts through omnimidi,

**Screenshots/Videos**
Video:

**Environment**
 - Operating system: Windows 10
 - CPU: i don't know...
 - RAM: 279GB
 - MIDI application: Kiva (Version 1.1.15)
 - Version of the driver: i don't know...

**Additional context**
When i patch an application, the application i patched automatically closes.

https://user-images.githubusercontent.com/116571696/217439548-04ba9a00-4c18-48d5-beb4-768093c086e5.mp4

**Note**
I needed to reinstall my midi player, almost delete all my user data on omnimidi, uninstall omnimidi, wanted to add a soundfont to PFA, reinstalled omnimidi, and now i'm here

**Comment by KaleidonKep99** [comment]
Kiva sadly does not allow OmniMIDI to work properly, as it doesn't seem to unload BASS from memory.
This creates a DLL hell scenario, which causes OmniMIDI and Kiva to clash when loading different versions of the same library in memory.
