### ISSUE TITLE
MIDI player crashes when minimizing / full screening when a different program is outputting MIDI signals is in the background

### ISSUE THREAD

**Issue by n0b0py** [KaleidonKep99/Keppy-s-MIDI-Driver#249]
**Problem**
When open any midi program (that plays midis) and minimize it and launch a new program outputting or using midi signals while the MIDI is playing, the MIDI player freezes and crashes (without that port being selected) .
**Steps to reproduce**
1. Play any MIDI in a MIDI player
2. Minimize MIDI player and open a program that creates MIDI signals
3. Start making MIDI signals from a different program

**Expected behavior**
I expected it to not crash, and be able to run with excess MIDI signals in the background.

**Screenshots/Videos**
Sorry, my video recorder is having issues.

**Environment**
 - Operating system: Windows 10
 - CPU: Intel Core i7-6700tT @ 2.80 GHz, overclocked at 3.30GHz with 4 Cores
 - GPU: NVIDIA GeForce GTX 960 8.0GB Memory
 - RAM: 7.9GB
 - MIDI application: PianoFromAbove (Version 1.1.0)
 - Version of the driver: Latest version
 - SSD/HDD Capacity: 98.0GB/99.4GB & 119MB/399MB

**Comment by KaleidonKep99** [comment]
Sorry for taking so long.

It should be fixed now. Let me know if you still have problems.
