### ISSUE TITLE
Omnimidi Causing Programs to Crash

### ISSUE THREAD

**Issue by ar06x** [KaleidonKep99/Keppy-s-MIDI-Driver#250]
**Problem**
Any program that attempts to connect to omnimidi will crash. The programs that seem to be affected by this issue are one's that do not use KDMAPI. For example, if any Chromium based browser tries to connect to omnimidi, or in my case get any info about it, the browser will crash.

**Steps to reproduce**
1. Open the browser
2. Browser crashes

**Expected behavior**
For midi connections in my browser to be listed properly without a crash happening.

**Screenshots/Videos**
If you need a video, I will be happy to provide one if asked. 

**Environment**
 - Operating system: `Windows 11 Pro x86_64`
 - CPU: `AMD Ryzen 7 5700X (16) @ 3.600GHz`
 - RAM: `32678MiB (32GB)`
 - MIDI application: `Chromium (Version 112.0.5615.138)`
 - Version of the driver: `14.7.1.0`

**Additional context**
Related to previous Issue #195

**Comment by ar06x** [comment]
I should note I was visiting a site that has midi input

**Comment by ar06x** [comment]
Update:
I tried running Kiva, which can use KDMAPI. I then switched to KDMAPI, and experienced the worst audio I've ever heard from OmniMidi. There is so much crackling/popping that it's hard to even hear the midi playing. This is the same config I had in the last stable release of OmniMidi, so I haven't changed anything on my end. Switching to WinMM seems to have the same issue in Kiva. Note: Kiva does pop up a warning regarding DLL hell

**Comment by ar06x** [comment]
Another update:
Reverting back to previous versions of OmniMidi doesn't fix the issue unfortunately. I have no idea why either. OmniMidi was working great before I updated to `14.7.1.0`, but now even reverting back doesn't fix the issue. I've uninstalled it from my system and reinstalled it, but the issue still happens. Maybe the uninstall didn't clean up everything OmniMidi left? I'm not completely sure

**Comment by KaleidonKep99** [comment]
Hi.

This issue seems to be extremely random, I tried reproducing it on my end but **all** browsers seem to be able to interface with the driver just fine.
That doesn't mean that the issue does not exist, other users seem to have it, but it doesn't seem to be that common either...
Would you be able to send a debug log of the driver? You can enable it from the Settings tab.

**Comment by ar06x** [comment]
~~Hey, sorry for the late response. Where exactly would I get the debug log from? I'm looking in settings under "Debug and Legacy settings" and can't seem to find it~~

**Comment by ar06x** [comment]
[chrome.exe (Debug output).txt](https://github.com/KeppySoftware/OmniMIDI/files/11693053/chrome.exe.Debug.output.txt)

**Comment by KaleidonKep99** [comment]
It seems to crash on basswasapi.dll... I'll look into it.

**Comment by ar06x** [comment]
Alright, thanks

**Comment by ar06x** [comment]
@KaleidonKep99 
I managed to fix it by downloading the basswasapi.dll from https://www.un4seen.com/ (BASSWASAPI)
I then guessed which parts of omnimidi were using x64 or x32 based on file size. 
`C:\Windows\System32\OmniMIDI` appeared to be using x64, so I replaced `basswasapi.dll` with the new (x64) one
`C:\Windows\SysWOW64\OmniMIDI` appeared to be using x32, so I replaced the dll with the new x32 dll. 
This appeared to solve my issue

**Comment by KaleidonKep99** [comment]
Sorry for not getting back to you earlier, and thank you for the finding!

I guess BASSWASAPI was having some issues with Chromium based browsers, since I still wasn't able to reproduce it on Firefox... (Even though Vivaldi **also** had no issues...)

I'll update the libraries in version 14.8!
