### ISSUE TITLE
I can’t even run OmniMIDI!

### ISSUE THREAD

**Issue by TheCloneOfAClone** [KaleidonKep99/Keppy-s-MIDI-Driver#251]
**Problem**
I can’t even run OmniMIDI due to an error that I can’t skip!

**Steps to reproduce**
If OmniMIDI is already installed:

1. Simply boot OmniMIDI from desktop.
2. An error that says ”Configurator Error - An error has occurred while loading the Configurator’s Settings” Pops-up.
3. Press X or “OK” and the same exact error pops-up - you can’t close that error without terminating OmniMIDI via Task Manager, and even then you still can’t start OmniMIDI.

While in the OmniMIDI installer:

1: Go through the installer as usual.
2: Once it goes through the “Installing registery keys” step of the installation process, the same error pops-up - again, still can’t skip it.
3: If you exit out of the error, it appears again - but since the installer thinks that everything went as usual, it says that it has finished installing - which isn’t the case.

**Expected behavior**
To install/run OmniMIDI as usual without an error blocking my path.

**Screenshots/Videos**
![](https://media.discordapp.net/attachments/485891140659183650/1101633946040672388/IMG_1825.jpg)
A screenshot of the error after the installer “finishes installing” OmniMIDI.

**Environment**
 - Operating system: Windows 11
 - CPU: Intel Pentium Silver
 - RAM: 4GB
 - MIDI application: Domino MIDI Editor; but it doesn’t matter since I can’t even run OmniMIDI at all!

**Additional context**
I can’t even run OmniMIDI! Please help!

**Comment by KaleidonKep99** [comment]
Should be fixed in 14.8.
