### ISSUE TITLE
Offline installer 

### ISSUE THREAD

**Issue by SiriusTheKittenLab** [KaleidonKep99/Keppy-s-MIDI-Driver#254]
Offline installer that includes net 4.0 for systems without network. Might be helpful for older Windows 7/Vista systems that cannot correctly connect to network even with network

**Comment by KaleidonKep99** [comment]
This is an invalid issue.

You can get the setup here anyway: https://www.microsoft.com/en-US/download/details.aspx?id=17718

**Comment by SiriusTheKittenLab** [comment]
I opened this as a suggestion which is clear i'm sure

**Comment by SiriusTheKittenLab** [comment]
the issue thing had "suggestion" so I selected it

**Comment by SiriusTheKittenLab** [comment]
either way on Windows 7 even with net offline installed it still says "cannot connect" because it tries to install the already installed on recent omni midi versons
