### ISSUE TITLE
Linear attack phase & Linear decay/release phases setting logic inverted?

### ISSUE THREAD

**Issue by minelolpride** [KaleidonKep99/Keppy-s-MIDI-Driver#256]
**Problem**
In 14.6 CR58 you added support for linear attack phase & linear decay/release phases to be used on SF2 soundfonts, leaving the options disabled by default. The control logic for both of the settings are inverted. (so it's off when you go to "enable" it)

Found by checking the audio during playback against the audio produces from 14.6 CR55 (the previous pre-release). This occurs as of 14.7.1.

**Steps to reproduce**
1. Install OM 14.6.0.58 or later
2. Load a soundfont with little release time such as [this one](https://mega.nz/file/ngkWWQST#hvNYeAmNH0J6OgGzSd2j9ryueN9uYkmnF-XP4qzZdpk)
3. Load any MIDI with the linear phase settings disabled. (as they are by default)
4. Find out that the audio is slightly different. (the notes stick around for much longer than in previous versions)
5. Enable the linear phase settings & reload the MIDI
6. Observe playback audio parallel to that from previous versions.

**Expected behavior**
Linear phases should not be active when the relevant settings are disabled.

**Screenshots/Videos**
(No video at this time.)

**Environment**
 - Operating system: Windows 10
 - CPU: Ryzen 7 5800X3D
 - RAM: 64GB DDR4-2666 (OC: DDR4-2800)
 - MIDI application: Piano From Above (Version 1.1.0)
 - Version of the driver: 14.7.1

**Additional context**
_I've somehow gaslit myself into not noticing this sooner_, but listening to audio from a converter & later listening to a MIDI with an old familiar soundfont alerted me to this being a thing.

**Comment by KaleidonKep99** [comment]
Will be fixed in 14.8.

**Comment by KaleidonKep99** [comment]
Fixed in 14.8+.
