### ISSUE TITLE
Too much reverb after updating to 14.8.0

### ISSUE THREAD

**Issue by Partitionhlep** [KaleidonKep99/Keppy-s-MIDI-Driver#260]
**Problem**
After updating OmniMIDI to 14.8.1 there's suddenly more reverb than usual. There wasn't this much reverb on OmniMIDI 14.7.1 and below.

**Steps to reproduce**
1. Install OmniMIDI 14.8.0
2. Play literally any midi on any program using OmniMIDI (with soundfont with reverb hardcoded, e.g. arachno)

**Expected behavior**
A normal amount of reverb

**Screenshots/Videos**
https://github.com/KeppySoftware/OmniMIDI/assets/133023998/810b947f-bc6b-42ed-8155-b30cdfe82b4a

**Environment**
 - Operating system: Windows 11 Pro 21H2
 - CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (AMD64 architecture)
 - RAM: 8GB
 - MIDI application: Piano From Above 1.1.0
 - Version of the driver: 14.8.1

**Additional Context**
This issue is present on later versions, except for 14.999.999.1 (v15 Alpha 1).
Reverb and chorus is also disabled in settings.

**Comment by B00ie23** [comment]
Untick linear decay and release phases in volume envelopes, then restart the audio stream. The "reverb" should no longer be present after applying the change.

![OmniMIDIConfigurator_POWA1vvWYo](https://github.com/KeppySoftware/OmniMIDI/assets/45867359/2a8e2c44-8ebf-4139-9bf8-2f9b1d7285cd)
_(this setting)_

Edit: I just read that this is actually a fix, refer to [this post](https://github.com/KeppySoftware/OmniMIDI/issues/256) for details.

**Comment by Partitionhlep** [comment]
it worked, thanks
