### ISSUE TITLE
Permanent sustain

### ISSUE THREAD

**Issue by ThreeDeeJay** [KaleidonKep99/Keppy-s-MIDI-Driver#262]
**Problem**
Notes keep playing after letting go of the keys.

**Steps to reproduce**
1. Set up Synthesia to use OmniMIDI [14.8](https://github.com/KeppySoftware/OmniMIDI/releases/tag/14.8.0.0)+ as MIDI output (probably happens with other apps, and it happened with multiple soundfonts so I don't think they're the cause either)
2. Click test or press keyboard keys to test the piano output and the notes will keep going after letting go.
![image](https://github.com/KeppySoftware/OmniMIDI/assets/71472458/a469d592-5f69-42a4-8c14-0187e284f1a4)

**Expected behavior**
Version [14.7.1](https://github.com/KeppySoftware/OmniMIDI/releases/tag/14.7.1.0) and earlier don't have this issue, so it's likely some change introduced in [14.8](https://github.com/KeppySoftware/OmniMIDI/releases/tag/14.8.0.0) (perhaps #256?), where the issue starts to happen. 

**Screenshots/Videos**
On a side note, there's this warning, which I usually just ignore because it'd usually just fine anyway, at least on 14.7.1 or earlier.
![image](https://github.com/KeppySoftware/OmniMIDI/assets/71472458/0dbbafa8-7a74-4278-abd2-6e79b1448b41)
Would be nice to get rid of that warning permanently too

**Environment**
 - MIDI application: Synthesia (Version 10.9.5893)
 - Version of the driver: 14.8

**Comment by zvikadror** [comment]
Verified on Windows 7.
Thank you for reporting this @ThreeDeeJay !
I've updated this morning to 14.8.latest-stable within the app, and the added sustain drove me crazy.
I compared with same SF2 files put under another sampler to verify its not my keyboard's fault :)
Tried to remove and re-register the driver, eventually removed and installed older 14.7.1 to play "normally".

**Comment by Danfun64** [comment]
I believe I might have bumped into this issue as well when playing Doom 2 with the most recent version of OmniMidi. The notes in the title wouldn't stop playing.

Version 14.8.4

**Comment by ThreeDeeJay** [comment]
It seems to have been fixed as of [14.8.5.0](https://github.com/KeppySoftware/OmniMIDI/releases/tag/14.8.5.0):
> Resetting the settings in OmniMIDI should now get rid of the weird linear attack/sustain behavior.

So I'll go ahead and close this issue. Thanks, Keppy!
