### ISSUE TITLE
Broken Windows XP SP2 x64 Support on the version that readded  support

### ISSUE THREAD

**Issue by SiriusTheKittenLab** [KaleidonKep99/Keppy-s-MIDI-Driver#272]
I used the first version supported on Windows XP  x64 Edition (SP2)

**Steps to reproduce**
1. Install Windows XP Service Pack 2 on a ***VIRTUALBOX*** VM - Install the nessesities (Visual C++ 2010)
2. Install the version of synth that readded the Windows XP SP2 x64
3. During the install, you will see this error: "KeppyDriverConfigurator.exe - Application Error"
                                                                      The application failed to initialize properly (0xc0000135). Click on OK to terminate the application.

**Expected behavior**
Did not show the error, and execute the application when it finishes without the error

**Screenshots/Videos**
None

**Environment**
 - Operating system: Windows XP Service Pack 2 x64 Edition in a Virtual Machine
 - CPU: Intel Core i3 8130U @ 2.2GHz
 - RAM: 2171MB (Virtual Machine)
 - MIDI application: Keppy's Driver (3.3.0.0)
 - Version of the driver: 3.3.0.0

**Additional context**
None

**Comment by SiriusTheKittenLab** [comment]
Please do not ask why im using this in a VM. I want to

**Comment by SiriusTheKittenLab** [comment]
I did not mean tto close it

**Comment by KaleidonKep99** [comment]
The last version that supports Windows XP is OmniMIDI 8.3.

Download: https://github.com/KeppySoftware/OmniMIDI/releases/tag/8.3.0.0
